jamaljsr/polar

- TODO.md
- docker/README.md
- src/components/designer/default/DefaultSidebar.spec.tsx
- src/components/designer/default/DefaultSidebar.tsx
- src/lib/docker/composeFile.spec.ts
- src/lib/docker/nodeTemplates.spec.ts
- src/store/models/designer.ts
- src/store/models/network.spec.ts
- src/store/models/network.ts
- src/types/index.ts
- src/utils/network.ts
Docker hub is down, so I cannot push the new LND image. Don't merge this until the v0.8.0-beta image has been pushed.
```
docker build --build-arg LND_VERSION=0.8.0-beta -t polarlightning/lnd:0.8.0-beta .
```
> feat(lnd): add support for multiple versions of LND nodes including v0.8.0

- TODO.md
- electron/lnd/lndProxyServer.ts
- src/components/designer/lnd/actions/OpenChannelModal.spec.tsx
- src/lib/ipc/ipcService.ts
- src/shared/ipcChannels.ts
- src/shared/lndDefaults.ts
- src/store/models/lnd.ts
Closes #195 
Fixes the sidebar displaying "undefined sats" when the actual value is 0.
1. Open a new channel between two nodes
2. Confirm the channel in the designer is colored green (active)
3. Click on the channel
4. Confirm the Source/Destination balances do not say "undefined"
> fix(channels): fix channel info showing "undefined sats" 

- src/components/common/NavMenu.spec.tsx
- src/components/common/NavMenu.tsx
- src/components/home/GetStarted.tsx
- src/components/layouts/AppLayout.spec.tsx
- src/components/network/NetworkActions.tsx
- src/components/network/NewNetwork.spec.tsx
- src/components/network/NewNetwork.tsx
- src/components/routing/Routes.spec.tsx
- src/components/routing/Routes.tsx
- src/components/routing/index.ts
- src/i18n/locales/en-US.json
- src/i18n/locales/es.json
- src/store/models/network.spec.ts
- src/store/models/network.ts
- src/utils/network.spec.ts
- src/utils/network.ts
Just polishing up small issues
> fix(ui): fix some minor UI issues

- package.json
- src/shared/lndDefaults.ts
- tools/lnrpcProto.js
- yarn.lock
See issue https://github.com/RadarTech/lnrpc/issues/59
> revert(lnrpc): downgrade lnrpc since the latest doesn't work on windows

- src/components/designer/lnd/actions/OpenChannelModal.tsx
> feat(ui): disable "Close channel" button if opening channel to self

- yarn.lock
> chore(deps): update yarn.lock to fix native dependency builds

- package.json
- yarn.lock
Updated dependencies:
- `react-scripts` to v3.3.0
- `eslint` to v6.6.0
- `webpack` to v4.41.2
> chore(deps): update dependency react-scripts to v3.3.0

- .github/workflows/main.yml
- .renovaterc
- package.json
- yarn.lock
Improve and fix release publishing in CI builds
> ci(github): improve CI builds

- TODO.md
- src/lib/docker/dockerService.spec.ts
- src/lib/docker/dockerService.ts
- src/store/models/app.spec.ts
- src/store/models/network.ts
- src/types/index.ts
- src/utils/constants.ts
- src/utils/migrations.ts
- src/utils/network.ts
This just fixes some small compatibility issues when loading networks from v0.1.0 in the new version.
> fix(networks): fix issues found when loading networks from the previous app version

- .github/ISSUE_TEMPLATE/bug_report.md
Minor spelling error fix and added Polar version field to bug template document.
> docs: fix spelling and add Polar version field to bug template

- CHANGELOG.md
- README.md
- package.json
Packaging up a new release which includes the toggle for light/dark mode
> chore(release): bump version to v0.2.1 and update changelog

- src/components/designer/SidebarCard.tsx
> fix(ui): make SidebarCard scrollable

- src/lib/bitcoin/bitcoindService.spec.ts
- src/lib/bitcoin/bitcoindService.ts
> fix: handle errors in Bitcoind logger

- src/shared/lndDefaults.ts
> fix: make sure localBalance is never undefined for pending channel

- CONTRIBUTING.md
- README.md
Closes #291 
Adds some documentation explaining how to setup your local dev environment to package Polar from source code and open PRs.
> docs: add CONTRIBUTING documentation

- src/components/designer/lightning/LightningDetails.spec.tsx
- src/i18n/locales/en-US.json
> fix(i18n): fix typo in English translations

- CHANGELOG.md
- README.md
- package.json
> chore(release): bump version to v1.0.0

- CONTRIBUTING.md
Small typo fix.
Simple typo that I noticed.
[Description of your changes go here. Please provide both casual and technical explanations.]
1. None...just proofread it!
N/A
> Small typo

- CONTRIBUTING.md
Small typo error
Small typo error
[Description of your changes go here. Please provide both casual and technical explanations.]
No, just a typo!
> Small typo error

- CHANGELOG.md
- README.md
- package.json
> chore(release): bump version to v1.0.1

- docker/nodes.json
- src/utils/constants.ts
Looking to test coin selection in this release. Full release notes here: https://github.com/lightningnetwork/lnd/releases/tag/v0.11.0-beta.rc4
> feat(lnd): add support for LND v0.11.0-beta.rc4

- src/components/designer/custom/NodeInner.tsx
Adds a grab cursor for nodes in the flowchart
1. Hover a node
> style(node): add hover state for node

- src/store/index.ts
Updates a dead link in the code
> chore: update dead link

- CHANGELOG.md
- README.md
- package.json
> chore(release): bump version to v1.3.0 and update changelog

- docs/custom-nodes.md
Fix typo at line 3.
[Description of your changes go here. Please provide both casual and technical explanations.]
1. Steps
2. To
3. Test
> Update custom-nodes.md - fix typo

- README.md
- docker/README.md
- docker/nodes.json
- src/utils/constants.ts
This PR adds support for LND v0.15.0-beta
> feat(images): add support for LND v0.15.0-beta

- CONTRIBUTING.md
Removing 2 duplicate lines from CONTRIBUTING
> fix(docs): removing duplicates from CONTRIBUTING file

- CHANGELOG.md
- README.md
- package.json
> chore(release): bump version to v1.4.0 and update changelog

- README.md
- docker/README.md
- docker/nodes.json
- src/utils/constants.ts
> feat(images): add support for LND v0.15.2-beta

- README.md
- docker/README.md
- docker/nodes.json
- src/utils/constants.ts
Closes #616 
Adds support for LND v0.15.3-beta and v0.15.4-beta
> feat(images): add support for LND v0.15.3-beta and v0.15.4-beta

- docker/README.md
- docker/nodes.json
- src/utils/constants.ts
Adds support for LND v0.15.5-beta.rc1
> feat(images): add support for LND v0.15.5-beta.rc1

- src/components/designer/taro/actions/SendAssetModal.tsx
- src/i18n/locales/en-US.json
-Increase the lightning wallet balance check by 2x.
-Send button now has loading state.
-Added missing error state
> fix(send-asset-modal): bug fixes

- docker/README.md
- docker/bitcoind/Dockerfile
- docker/clightning/Dockerfile
- docker/clightning/Dockerfile.arm64
- docker/eclair/Dockerfile
- docker/lnd/Dockerfile
Closes #532 
- Adds docker support for arm64 support for eclair and c-lightning docker images
- Updates the readme to show how this images can be built using the `docker buildx` command
> Feature add multiarch docker images

- README.md
- docker/README.md
- docker/nodes.json
- src/utils/constants.ts
Pushed Docker images and added support for LND v0.16.1-beta and v0.16.2-beta.
> feat(images): add support for LND v0.16.1-beta and v0.16.2-beta

- CHANGELOG.md
- README.md
- RELEASE.md
- package.json
> chore(release): bump version to v2.0.0 and update changelog

- README.md
- docker/README.md
- docker/nodes.json
- src/components/designer/tap/actions/ChangeTapBackendModal.spec.tsx
- src/store/models/designer.spec.ts
- src/utils/constants.ts
- src/utils/tests/helpers.ts
Adds support for Taproot Assets v0.2.3
> feat(images): add support for Taproot Assets v0.2.3

- docker/README.md
- docker/nodes.json
- src/utils/constants.ts
Adds support for LND v0.17.0-beta.rc1
> feat(images): add support for LND v0.17.0-beta.rc1

- docker/nodes.json
- src/utils/constants.ts
Adds support for LND v0.17.0-beta.rc2
> feat(images): add support for LND v0.17.0-beta.rc2

- CHANGELOG.md
- README.md
- package.json
> chore(release): bump version to v2.2.0 and update changelog

- CONTRIBUTING.md
- e2e/Network.e2e.ts
- src/lib/docker/composeFile.spec.ts
- src/lib/ipc/ipcService.spec.ts
fix some comments
1. Steps
2. To
3. Test
> chore: fix some comments

- docker/README.md
- docker/nodes.json
- src/utils/constants.ts
Adds support for LND v0.18.1-beta and v0.18.2-beta.
> feat(images): add support for LND v0.18.2-beta

- src/components/designer/lightning/actions/OpenChannelModal.spec.tsx
- src/lib/lightning/eclair/eclairApi.spec.ts
The PR adds test for the scenario when`Make the channel private` checkbox is selected
> test(OpenChannelModal): added test case for private channel selection

- docker/README.md
- docker/litd/Dockerfile
- src/components/common/AdvancedOptionsButton.tsx
- src/components/nodeImages/ManagedImageModal.tsx
- src/lib/docker/composeFile.spec.ts
- src/lib/docker/composeFile.ts
- src/store/models/lit.ts
- src/utils/constants.ts
- src/utils/network.ts
- src/utils/strings.spec.ts
- src/utils/strings.ts
Adds support for `tapd` v0.4.0-alpha.rc4 and `litd` v0.13.99-alpha.rc4
> feat(images): add support for tapd v0.4.0-alpha.rc4

- README.md
- docker/README.md
- docker/litd/src.Dockerfile
- docker/tapd/src.Dockerfile
- package.json
- src/components/designer/lightning/actions/OpenChannelModal.spec.tsx
- src/lib/docker/dockerService.ts
- src/shared/tapdDefaults.ts
- src/store/models/designer.spec.ts
- src/store/models/tap.ts
- src/utils/constants.ts
- src/utils/network.spec.ts
- src/utils/tests/helpers.ts
- yarn.lock
Updated `litd` and `tapd` to that latest versions.
> feat(litd): update litd/tapd deps to the latest versions

- README.md
- docker/README.md
- docker/bitcoind/Dockerfile
- src/lib/lightning/lnd/mappers.ts
- src/utils/chart.ts
- src/utils/constants.ts
Adds support for the latest node versions.
- [LND](https://github.com/lightningnetwork/lnd) - v0.18.3
- [Core Lightning](https://github.com/ElementsProject/lightning) - v24.08.1
- [Bitcoin Core](https://github.com/bitcoin/bitcoin) - v28.0
- [Terminal](https://github.com/lightninglabs/lightning-terminal) - v0.13.995
> feat(images): add support for the latest node versions

- docker/README.md
- src/store/models/designer.spec.ts
- src/utils/constants.ts
- src/utils/network.spec.ts
- src/utils/tests/helpers.ts
Updates the nodes to the latest versions
- lnd v0.18.4-beta.rc1
- tapd v0.5.0-alpha.rc1
> feat(images): update to lnd v0.18.4-beta.rc1 and tapd v0.5.0-alpha.rc1

- CHANGELOG.md
- README.md
- docker/nodes.json
- package.json
Prepping for release of v3.2.0
> chore(release): bump version to v3.2.0 and update changelog

- README.md
- docker/README.md
- docker/nodes.json
- src/utils/constants.ts
Adds support for lnd v0.19.0 and tapd v0.6.0-rc2
> feat(images): add support for lnd v0.19.0 and tapd v0.6.0-rc2

- src/utils/constants.ts
- src/utils/network.ts
Closes #1179
This PR binds the gRPC server in CLN to the host's localhost.
> feat: bind CLN container to host
