jamaljsr/polar

.github/workflows/main.yml, package.json, yarn.lock
The upgrade of electron to 6.1.0 causes an issue with compiling the native grpc module.
The upgrade of testcafe to 1.6.0 causes e2e tests to fail.
This PR also re-enables e2e tests to run only on macOS because it doesn't work on ubuntu and windows is very flaky.
=> revert(deps): revert updates of electron and testcafe

package.json, src/components/designer/NetworkDesigner.spec.tsx, src/components/designer/bitcoind/MineBlocksInput.spec.tsx, yarn.lock
These dependency updates must be made altogether because the version of webpack used by this project must match the version used by react-scripts. The renovate bot doesn't know how to do them both at the same time. testcafe needed to also be updated due to a [bug](https://github.com/DevExpress/testcafe/issues/4435).
=> chore(deps): update dependencies react-scripts, webpack, and testcafe

src/components/network/NetworkView.spec.tsx, src/components/network/NetworkView.tsx, src/i18n/locales/en-US.json, src/i18n/locales/es.json, src/lib/docker/dockerService.spec.ts, src/lib/docker/dockerService.ts, src/store/models/app.ts, src/store/models/network.spec.ts, src/store/models/network.ts, src/types/index.ts, src/utils/constants.ts, src/utils/network.ts, src/utils/tests.tsx
Displays a banner when the docker images needed to start a network have not been downloaded yet.
=> feat(network): display slow start notice if docker images need to be pulled

docker/README.md, docker/bitcoind/Dockerfile, docker/bitcoind/docker-entrypoint.sh, docker/lnd/Dockerfile, docker/lnd/docker-entrypoint.sh, package.json, src/__mocks__/fs-extra.js, src/components/home/DetectDockerModal.spec.tsx, src/components/home/DetectDockerModal.tsx, src/lib/docker/composeFile.ts, src/lib/docker/dockerService.spec.ts, src/lib/docker/dockerService.ts, src/lib/docker/nodeTemplates.ts, src/utils/system.spec.ts, src/utils/system.ts
Partially fixes #227
Docker containers on linux share file permissions with hosts. Assigning the same uid/gid from the host user to the container user ensures that the files can be read/write from both sides.
There's a really good write-up [here](https://www.berthon.eu/2018/containers-volumes-and-file-permissions/).
1. Run the app on a linux
2. Confirm the nodes boot up successfully
=> fix(docker): fix containers not starting up on linux

docker/README.md, src/components/network/NetworkView.spec.tsx, src/lib/docker/dockerService.ts, src/lib/docker/nodeTemplates.ts, src/shared/types.ts, src/utils/config.ts, src/utils/constants.ts
This PR adds support for c-lightning v0.8.0 which was recently released. 
With c-lighting changing the folder structure of their dataDir in v0.8.0, lightningd was unable to create the lightning-rpc socket file due to 'path too long' errors on Mac. The node data was originally stored in ~/Library/Application Support/polar/data/networks/. This has now been changed to ~/.polar on all OS's. Due to this change, networks that were created in Polar v0.1.0 will no longer be displayed in the app. They will need to be manually moved or re-created.
To move the previous networks to the new location, you must stop any running networks and close the Polar app. Then move the 'networks' folder depending on your OS to the new location:
Location in v0.1.0
Mac: ~/Library/Application …
=> feat(clightning): add support for c-lightning v0.8.0

docker/clightning/Dockerfile, src/components/terminal/DockerTerminal.tsx, src/lib/lightning/clightning/clightningService.ts, src/store/models/lightning.ts, src/utils/constants.ts
Just fixing up some small bugs found when testing on Windows and Linux
- fix LND channels remaining pending after close
- add terminal alias so lightning-cli always uses regtest
- fix reopened c-lightning channels not showing in the designer
- fix race condition during c-lightning channel opening with deposit
=> fix(channels): fix a few issues found during cross-platform testing

src/components/designer/bitcoind/ConnectTab.tsx, src/i18n/locales/en-US.json, src/lib/docker/composeFile.ts, src/lib/docker/nodeTemplates.spec.ts, src/lib/docker/nodeTemplates.ts, src/shared/types.ts, src/utils/constants.ts, src/utils/network.spec.ts, src/utils/network.ts
Closes #296 
This PR makes bitcoind's ZeroMQ servers reachable on LAN instead of only via the private network (172.x.x.x).
Some changes had to be made in `createBitcoindNetworkNode()` to be able to accomplish this as the ZeroMQ block port would otherwise collide with the ZeroMQ tx port (because default port numbers are just after one another, 28334 and 28335, the "+ id"-way won't work anymore ).
According to the new code, the ZeroMQ block port will always start 1 above the highest ZeroMQ tx port found (and Tx port 2 above).  
A similar issue can also appear in `getOpenPorts()`. As the port test is done individually and not together, `getOpenPorts()` could return the same port number for both ZeroMQ block and ZeroMQ tx.
I've made a new function where you pass in a group of ports to be …
=> feat: make bitcoind's ZeroMQ servers reachable on LAN

src/components/home/NetworkCard.tsx, src/components/network/NetworkView.spec.tsx, src/components/network/NetworkView.tsx, src/i18n/locales/en-US.json, src/store/models/bitcoind.ts, src/store/models/lightning.ts
Fixes an issue where global state data from one network is leftover and used by another network. This causes some errors to be thrown when refreshing the network from all nodes.
=> fix(designer): fix corrupt redux state causing errors

TODO.md, src/components/terminal/DockerTerminal.tsx
Closes #308 
This PR fixes a bug in the terminal with long wrapping text. The overflow characters would be displayed on the same line instead of the next. This cause the whole command to be unreadable.
1. Open a terminal for one of the nodes
2. Type or paste in a long command
3. Confirm that it wraps to the next line properly
Before
After
=> fix(terminal): fix broken line wrapping for long commands

src/components/common/NavMenu.tsx, src/components/designer/SidebarCard.tsx, src/components/designer/bitcoind/ActionsTab.tsx, src/components/designer/lightning/ActionsTab.tsx, src/components/designer/link/Channel.spec.tsx, src/components/designer/link/CloseChannelButton.tsx, src/components/network/NewNetwork.tsx, src/components/nodeImages/CustomImageModal.spec.tsx, src/components/nodeImages/CustomImageModal.tsx, src/i18n/locales/en-US.json, src/index.tsx, src/store/models/bitcoind.ts, src/store/models/network.spec.ts, src/store/models/network.ts
This PR contains multiple fixes for issues found when testing on all platforms (Mac, Windows and Linux).
- view logs shows infinite loader (linux)
- don't show incompatible custom nodes in the new image modal (windows)
- don't show incompatible custom nodes in the NewNetwork screen (windows)
- add eclair to the custom node dropdown
- for eclair to start successfully, always mine 1 block when the network is started
- do not allow importing networks with missing images
- in NewNetwork, change custom nodes row to 4 columns
- prevent close channel for stopped node
- use styled scrollbars throughout the whole app
=> Fix OS compatibility issues

src/i18n/locales/en-US.json, src/lib/docker/composeFile.ts, src/utils/constants.ts
Closes #352
Adds the LND node's docker container name as a `--tlsextradomain` command line argument to support RPC connections from external docker networks.
=> fix(lnd): add docker container name as tlsextradomain

src/components/designer/bitcoind/ConnectTab.tsx, src/i18n/locales/en-US.json, src/lib/docker/composeFile.ts, src/lib/docker/nodeTemplates.spec.ts, src/lib/docker/nodeTemplates.ts, src/shared/types.ts, src/utils/constants.ts, src/utils/network.spec.ts, src/utils/network.ts
Closes #370 
Exposes the Bitcoin Core P2P port on the host to allow other applications on the local network to join the Polar Bitcoin network.
1. Create a Polar network with a Bitcoin node
2. Copy the P2P connection string
3. Run `bitcoin-cli addnode <connection string> onetry` on a regtest node on the local network
4. Run `bitcoin-cli getpeerinfo` on the local network node to verify you are connected
=> feat(bitcoind): expose Bitcoin Core P2P port

src/components/designer/NetworkDesigner.spec.tsx, src/components/designer/NetworkDesigner.tsx, src/store/models/designer.spec.ts, src/store/models/designer.ts, src/utils/chart.ts
Add the ability to zoom in & out the designer and nodes to more easily visualize the network. 
1. Click on a network
1. Click on the zoom icons on the bottom right of the canvas
1. Use the mouse wheel scroll to also adjust the zoom level
1. Drag a new node onto the canvas to ensure proper placement
=> feat(chart): add zoom buttons to the designer

src/components/designer/lightning/ConnectTab.tsx
Copying the `P2P Internal` value to the clipboard was copying the value for `P2P External` instead.
1. Setup a network
2. Copy the value for `P2P Internal`
3. Paste the value somewhere (should match the displayed value in the app)
=> fix(lnd): fixes clipboard copy value for p2pLnUrlInternal

docs/custom-nodes.md
Updates instructions for how to build custom eclair image to work with latest version.
The other Dockerfile probably also needs update. And the config option
```
--on-chain-fees.max-feerate-mismatch=100000
```
should now be
```
--on-chain-fees.feerate-tolerance.ratio-low=0.00001
--on-chain-fees.feerate-tolerance.ratio-high=10000.0
```
=> custom nodes: update to work with latest eclair

src/components/designer/lightning/ConnectTab.tsx, src/components/designer/lightning/LightningDetails.spec.tsx
The current LND [REST](https://api.lightning.community/rest) URL looks stale, so updating it to https://api.lightning.community/#lnd-rest-api-reference
Click on the REST link for an LND node
=> fix(lnd): correct REST url

src/utils/constants.ts
Exposes bitcoind's REST interface by default. No prob if this idea has been considered then discarded for any reason, feel free to close. Thank you!
Attempt to connect to bitcoind over REST on startup.
=> feat(bitcoind): expose REST interface by default

CHANGELOG.md, README.md, package.json
Packaging up a new release due to a breaking change in `bitcoind` v0.21.0
=> chore(release): bump version to v1.2.0

src/lib/bitcoin/bitcoindService.ts, src/lib/lightning/clightning/clightningService.ts, src/lib/lightning/eclair/eclairService.ts, src/lib/lightning/lnd/lndService.ts
Closes #464 
This PR just increases the node startup timeout to accomodate for systems with slower Docker performance.
=> fix(nodes): increase node startup timeout from 60 to 120 secs

src/components/common/Loader.spec.tsx, src/components/common/Loader.tsx, src/components/designer/custom/NodeInner.tsx
This PR fixes a minor CSS issue where the loading icon on the home screen did not animate in a full circle.
=> fix(home): fix loading animation on home screen

src/components/network/NewNetwork.spec.tsx, src/components/network/NewNetwork.tsx, src/i18n/locales/en-US.json
This PR adds proper error handling when creating a new network. It will now display an error toast message with more information as to why the creation failed. This should help diagnose the problem in #569.
=> fix(network): add error handling when creating a new network

src/components/designer/custom/NodeInner.tsx
This gives the user the ability to better see which node is selected. Before, a small shadow would highlight the selected node, but it's difficult to see with the light theme and almost impossible to see with the dark theme, at least in my monitor.
=> style(nodes): better visually know what node is selected

src/components/designer/Sidebar.tsx, src/components/designer/SyncButton.tsx, src/components/designer/default/DefaultSidebar.spec.tsx, src/components/designer/default/DefaultSidebar.tsx, src/components/network/NetworkActions.spec.tsx, src/components/network/NetworkActions.tsx, src/i18n/locales/en-US.json
This PR moves the Sync button from the top right of the sidebar to the toolbar next to the Quick Mine button in order to make it visible all the time. I've had discussions with some folks that didn't know this button even existed because it becomes hidden when a node is selected.
=> feat(designer): move sync button to actions toolbar

.electronbuildrc
Closes #564 
This PR updates the electron builder config to package an RPM file when creating release binaries.
=> chore(build): add RPM target to releases

src/lib/lightning/clightning/clightningService.ts
This PR fixes a minor race condition where sometimes Core Lightning will not return a funding txid immediately after opening a new channels. When this occurs, an error would be displayed in UI. The node would still be fully functional, but this fix just prevents the error from occurring.
=> fix(cln): handle error when funding txid is undefined

src/components/common/AdvancedOptionsModal.tsx, src/components/common/ImageUpdatesModal.tsx, src/components/common/StatusBadge.tsx, src/components/designer/bitcoind/actions/SendOnChainModal.tsx, src/components/designer/lightning/actions/ChangeBackendModal.tsx, src/components/designer/lightning/actions/CreateInvoiceModal.tsx, src/components/designer/lightning/actions/OpenChannelModal.tsx, src/components/designer/lightning/actions/PayInvoiceModal.tsx, src/components/home/DetectDockerModal.tsx, src/components/nodeImages/CustomImageModal.tsx, src/components/nodeImages/ManagedImageModal.tsx
This PR fixes a warning from the antd Modal component.
```
Warning: [antd: Modal] `visible` will be removed in next major version, please use `open` instead. 
```
It also fixes a small UI issue where the the spacing between the node name and status icon is incorrect.
=> fix(deps): change antd Modal visible props to open

src/components/terminal/DockerTerminal.tsx
Closes #531
* Added ability to increase/decrease the terminal's font size using keyboard shortcuts CTRL(+)+/- and CTRL(+)0 to reset font size
* Added copy/paste shortcuts using CTRL+SHIFT+(c/v)
* Fixed compilation issues relating to easy-peasy
1. Create / start a network
2. Launch a terminal on any LN node
3. Press CTRL(+)+ to increase font size, repeat to further increase until max allowed size
4. Press CTRL(+)- to decrease font size, repeat to further increase until min allowed size
5. Press CTRL(+)0 reset terminal's font size
6. Select some text and press CTRL(+)SHIFT(+)c to copy text to clipboard
7. Press CTRL(+)SHIFT(+)v to paste text from clipboard
=> feat(terminal): change font size and copy/paste using key shortcuts

src/utils/constants.ts
Closes #629
This pull request add compact block filter flags to bitcoind, which are used to serve light clients.
This can be helpful when testing and experimenting with mobile wallets that supports Neutrino like https://github.com/hsjoberg/blixt-wallet.
1. Create a bitcoind backend
2. Try to sync with a compatible Neutrino client
=> feat(bitcoind): Add Compact Filters support

src/store/models/taro.ts
Metadata needed to be a base64 string.
Should I write some tests for the asset info drawer? 
Meta Data was being encoded wrong. This is fixed.
1. Mint an asset
2. Add anything meta data field
3. Open AssetInfoDrawer. You should see meta data at top
=> fix(bad buffer): mint asset metadata

src/components/designer/taro/InfoTab.tsx, src/components/designer/taro/info/AssetsList.tsx, src/i18n/locales/en-US.json, src/utils/network.spec.ts, src/utils/network.ts
-taro nodes connect in order when dropped into the graph
-Taro info asset draw title says 'No Assets' if there are no assets
=> fix(general bugs): workflow fixes

README.md, package.json, src/components/dockerLogs/DockerLogs.tsx, src/components/terminal/DockerTerminal.tsx, src/lib/docker/dockerService.spec.ts, src/lib/docker/dockerService.ts, src/lib/lightning/clightning/clightningService.spec.ts, src/setupTests.js, yarn.lock
Docker Desktop for Mac no longer places the UNIX socket in the location `/var/run/docker.sock` for new installations. This prevents Polar from detecting the current version of Docker on the machine. This PR adds detection for the socket file in the new location `~/.docker/run/docker.sock`.
I also updated the README with notes on the currently outstanding issues with Docker. 
> ⚠️ **Important Docker Notes**
> 
> - On Mac & Windows, you must uncheck "Use Docker Compose V2" in Docker Desktop settings. We're waiting on Compose v2 support in the `docker-compose` NPM package (See [PDMLab/docker-compose#228](https://github.com/PDMLab/docker-compose/pull/228))
> - On Linux, Docker Desktop is currently not supported due to a significant change in how it handles file sharing between host and …
=> fix(docker): properly detect docker socket path

src/store/models/network.ts
Closes #508 
Currently, Polar caches the LND certificate & macaroon in memory to avoid going to disk for every RPC request. The side effect of this is that if the files are regenerated by deleting them then restarting LND, Polar continues to use the cached values. Because of this, Polar can no longer communicate with the node that now requires the updated values. 
This PR fixes this issue by clearing the cache when a node is stopped. When the node is started again, the cache will be empty and Polar will read the files from disk. The values will be cached in memory again until the node is stopped.
1. Create new network with 1 bitcoind and 1 lnd node
1. Start the network
1. Make note of the TLS cert hex value
1. Open terminal for lnd node (alice)
1. `rm /home/lnd/.lnd/tls.*`
1. Restart …
=> fix(network): clear RPC cache when nodes are stopped

src/lib/lightning/lnd/lndService.ts
Channel info now displays proper source and dest names
for pending channels
Closes #699
Channel links are proccessed twice resulting in data being clobbered.
1. Launch terminal for alice
2. Run ```lncli openchannel <bob-pubkey> 100000```
3. Check channel details
=> fix(chart.ts): pending channel display bug

src/__mocks__/docker-compose.js, src/lib/docker/composeFile.spec.ts, src/lib/docker/composeFile.ts, src/lib/docker/dockerService.spec.ts, src/lib/docker/dockerService.ts, src/lib/docker/nodeTemplates.ts
Closes #719 
Closes #614 
This PR adds support for Docker Compose v2 since v1 has officially been deprecated.
I also updated the compose file to give nodes more time to gracefully shutdown and added a `name` field to avoid the dirname of `1` being displayed in Docker Desktop.
=> docker: support docker-compose v2 + minor improvements

src/lib/docker/repoService.spec.ts, src/lib/docker/repoService.ts
Closes #723
Fixes an issue with updating node versions after a new implementation (ex: tapd) is added.
=> fix(docker): properly handle new node types in updates

src/lib/lightning/clightning/clightningService.spec.ts, src/lib/lightning/clightning/clightningService.ts
Closes #747 
Closes #758 
Fixes a bug where Core Lightning nodes are unable to peer with other nodes and therefore not able to open outbound channels.
1. Create a new network with two Core Lightning nodes
2. Start the network
3. Select a Core Lightning node
4. Click the Connect tab
5. Confirm the "P2P Internal" url contains the name of the node (ex: 02f...19f2132f@bob:9735) instead of `0.0.0.0`
=> fix(cln): use node hostname for P2P Internal url

src/utils/constants.ts
Hi Hi!
I am working on a one-click docker-compose setup for Blocktank, our open-source Synonym LSP solution. The goal is to make it work seamlessly with Polar so one can test and develop Blocktank without any issues.
To make it as seamless as possible, an additional LND default argument is required.
This PR adds `--tlsextradomain=host.docker.internal` to the LND default arguments. [host.docker.internal](https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host) is a special domain name in docker that resolves to the IP address of the host system. This allows other docker containers (not in the same docker network) to connect to the LND GRPC port exposed to the host machine.
Without this argument, LND TLS will reject the GRPC connection due to …
=> Add --tlsextradomain=host.docker.internal to lnd default args

src/utils/constants.ts
Closes #755
Adds the `--log-file` flag to Core Lightning nodes in order to log to disk in addition to stdout.
1. Create and start a new network with a Core Lightning Node
2. Right-click on the node and select "View Logs" to see the logs
3. Confirm the log file exists on your machine at `~/.polar/networks/1/volumes/c-lightning/bob/lightningd/debug.log`
=> feat(cln): save Core Lightning logs to disk

README.md
fixing broken download links for Mac and Windows.
also noticed that a new version was released yesterday, so updated the links to point to `v2.1.0`. 
pls let me know if keeping `v2.0.0` is intended and I'll update the PR.
=> fix download broken links + update download links to v2.1.0

e2e/helpers/index.ts, src/shared/utils.ts, src/utils/config.spec.ts, src/utils/config.ts
If and only if `~/.local/share/polar` exists, Polar will use it to store application data instead of `~/.polar`, abiding to the XDG specification (see https://wiki.archlinux.org/title/XDG_user_directories).
This is a backwards compatible update: users who have their data at `~/.polar` will NOT be affected. The `~/.local/share/polar` XDG-compliant directory is not created automatically and the user must create it manually to enable the new feature.
I tried to import `dataPath` from `src/utils/config` in `src/shared/utils` to avoid code duplication but it wouldn't compile and would complain `cannot resolve module 'utils/config'`. I tried to use a relative import, `import { dataPath } from '../utils/config'`, but the compiler would throw similar errors (it would not resolve …
=> feat: add xdg support

src/lib/lightning/eclair/eclairService.spec.ts, src/lib/lightning/eclair/eclairService.ts, src/lib/lightning/eclair/types.ts
This PR Closes #804
Some [ChannelData](https://github.com/jamaljsr/polar/blob/master/src/lib/lightning/eclair/types.ts#L46) properties for the Eclair node was updated for v0.9.0 when calling its [API](https://acinq.github.io/eclair/#channels-2) and this caused a bug when running that version. 
This PR updates the ChannelData properties to be compatible with v0.9.0, v0.8.0 and v0.7.0.
=> Fix: Bug: Eclair - Error in GUI when open channel #804

README.md, docker/README.md, docker/nodes.json, electron/tapd/tapdProxyServer.ts, package.json, src/components/designer/tap/actions/MintAssetModal.spec.tsx, src/lib/tap/tapd/tapdService.spec.ts, src/lib/tap/tapd/tapdService.ts, src/shared/tapdDefaults.ts, src/store/models/designer.spec.ts, src/store/models/tap.ts, src/utils/constants.ts, src/utils/tests/helpers.ts, yarn.lock
Adds support for `tapd` v0.3.3-alpha. There was a change in the `universerpc.AssetRoots` RPC which broke syncing universes in Polar. A new version of Polar will be necessary to run this `tapd` version. I'll hold off on merging this until the release is ready to ship.
=> feat(images): add support for tapd v0.3.3-alpha

src/components/designer/lightning/actions/OpenChannelModal.spec.tsx, src/components/designer/lightning/actions/OpenChannelModal.tsx
When you try to open a channel, the OpenChannelModal pops up and the checked box for `isPrivate` is unchecked - this should translate to false but it's undefined because it doesn't have a default value.
This PR fixes the default value for isPrivate to false.
=> fix(OpenChannelModal): added default value for isPrivate checkbox

docker/README.md, docker/nodes.json, src/utils/constants.ts
Add support for LND v0.18.0-beta.rc1. The docker image has already been pushed to Docker Hub.
=> feat(images): add support for LND v0.18.0-beta.rc1

src/components/network/NewNetwork.spec.tsx, src/components/network/NewNetwork.tsx, src/lib/settings/settingsService.spec.ts, src/store/models/app.spec.ts, src/store/models/app.ts, src/store/models/network.ts, src/types/index.ts
When repeatedly creating new networks for testing, I often want to use the same count of nodes that I used on the previously created network. It's a minor annoyance to have to change the counts each time. This PR just saves the node counts when you create a new network and uses those values the next time you go to the _New Network_ screen. 
1. Click _New Network_
2. Change the node counts to different values
3. Click _Create Network_
4. Delete the network
5. Restart Polar
6. Click _New Network_
7. Confirm the initial node counts are what you previously set
=> feat: remember node counts when creating new networks

README.md, docker/README.md, docker/nodes.json, src/utils/constants.ts, src/utils/tests/helpers.ts
Adds support for the following node versions:
- `tapd` v0.4.1-alpha  
- `litd` v0.13.991
The docker images have been pushed to Docker Hub.
=> feat(images): add support for tapd v0.4.1 and litd v0.13.991

docker/bitcoind/Dockerfile
We replace the bitcoin-cli bash-completion source link with the actual link. The previous one is broken and returns 404.
[Description of your changes go here. Please provide both casual and technical explanations.]
1. Steps
2. To
3. Test
=> fix: broken bitcoin-cli bash completion link

README.md, docker/README.md, docker/nodes.json, src/lib/lightning/clightning/clightningService.ts, src/utils/constants.ts, src/utils/tests/helpers.ts
Adds support for Core Lightning Node version 24.08
The docker [images](https://hub.docker.com/layers/polarlightning/clightning/24.08/images/sha256-f90244b2b8f1454bfb1177adbdb7b33b8613dcbe58660f69443c35b272cb6549?context=explore) have been pushed to Docker Hub.
=> feat(images): add support for CLN v24.08

.vscode/settings.json, docker/README.md, docker/nodes.json, src/store/models/designer.spec.ts, src/utils/constants.ts, src/utils/network.spec.ts, src/utils/tests/helpers.ts
Adds support for the following new node versions:
- LND v0.18.4-beta.rc2
- tapd v0.5.0-alpha.rc2
- litd v0.14.0-alpha.rc2
- Core Lightning v24.11
=> Update node implementations to their latest versions

README.md, docker/README.md, docker/nodes.json, src/store/models/designer.spec.ts, src/utils/constants.ts, src/utils/network.spec.ts, src/utils/tests/helpers.ts
Adds support for the latest lnd, tapd, and litd versions:
- `lnd` v0.18.5-beta
- `tapd` v0.5.1-alpha
- `litd` v0.14.1-alpha
=> Add support for the latest lnd, tapd, and litd versions

.renovaterc, package.json, yarn.lock
Closes #1164
The @renovate-bot updated the `@ant-design/icons` package to v6.0.0 in #1163 which broke the react app build. I went looking for a changelog of this package to see if  this breaking change was intentional, but I couldn't find any info about the new version in the [repo](https://github.com/ant-design/ant-design-icons). 
This PR just reverts that update. I also added this package to the @renovate-bot ignore list to prevent it from updating it again.
Run `yarn dev` and confirm that there are no errors running Polar in dev mode.
=> Revert antd icons upgrade

README.md
Closes #1202 
Not sure how that link became broken, but fixed it here.
=> docs: fix RPM link in README
